const galleryImages = document.querySelectorAll(".gallery-images");
const btnBefore = document.querySelector(".btn-before");
const btnAfter = document.querySelector(".btn-after");
const srebarnaText = document.querySelector(".srebarna-text");
const rilaText = document.querySelector(".rila-text");
const madaraText = document.querySelector(".madara-text");
const prohodnaText = document.querySelector(".prohodna-text");
const lakesText = document.querySelector(".lakes-text");
const belintashText = document.querySelector(".belintash-text");
const throatText = document.querySelector(".throat-text");
const bridgesText = document.querySelector(".bridges-text");
const image5 = document.querySelector(".img5");
const image6 = document.querySelector(".img6");
const image7 = document.querySelector(".img7");
const image8 = document.querySelector(".img8");
console.log(galleryImages);
console.log(btnBefore);

let currentImage = 0;
btnBefore.addEventListener("click", () => {
  console.log(currentImage);
  [...galleryImages].forEach((image) => {
    image.classList.remove("slide-left");
    image.classList.remove("slide-left1");
  });
  if (currentImage === -1) {
    currentImage = 7;
    console.log(currentImage);
  }
  if (currentImage === 8) {
    currentImage = 0;
    [...galleryImages].forEach((image) => {
      image.classList = "";
    });
    [...galleryImages].forEach((image) => {
      image.classList.add("gallery-images");
    });

    srebarnaText.classList = "";
    srebarnaText.classList.add("srebarna-text");
    rilaText.classList = "";
    rilaText.classList.add("rila-text");
    madaraText.classList = "";
    madaraText.classList.add("madara-text");
    prohodnaText.classList = "";
    prohodnaText.classList.add("prohodna-text");
    lakesText.classList = "";
    lakesText.classList.add("lakes-text");
    belintashText.classList = "";
    belintashText.classList.add("belintash-text");
    bridgesText.classList = "";
    bridgesText.classList.add("bridges-text");
    image5.classList = "";
    image5.classList.add("img5");
    image6.classList = "";
    image6.classList.add("img5");
    image6.classList.add("img6");
    image7.classList = "";
    image7.classList.add("img7");
    image8.classList = "";
    image8.classList.add("img8");
    lakesText.classList.add("hidden");
    belintashText.classList.add("hidden");
    throatText.classList.add("hidden");
    bridgesText.classList.add("hidden");
    image5.classList.add("hidden");
    image6.classList.add("hidden");
    image7.classList.add("hidden");
    image8.classList.add("hidden");
  }

  if (currentImage === 0) {
    galleryImages[currentImage].classList = "";
    galleryImages[currentImage].classList.add("gallery-images");
    galleryImages[currentImage].classList.add("slide-left");
    srebarnaText.classList = "";
    srebarnaText.classList.add("srebarna-text");
    srebarnaText.classList.add("slide-text");
    galleryImages[currentImage + 1].classList = "";
    galleryImages[currentImage + 1].classList.add("gallery-images");
    galleryImages[currentImage + 1].classList.add("slide-left1");
    rilaText.classList = "";
    rilaText.classList.add("rila-text");
    rilaText.classList.add("slide-text1");
    galleryImages[currentImage + 2].classList = "";
    galleryImages[currentImage + 2].classList.add("gallery-images");
    galleryImages[currentImage + 2].classList.add("slide-left1");
    madaraText.classList = "";
    madaraText.classList.add("madara-text");
    madaraText.classList.add("slide-text2");
    galleryImages[currentImage + 3].classList = "";
    galleryImages[currentImage + 3].classList.add("gallery-images");
    galleryImages[currentImage + 3].classList.add("slide-left1");
    prohodnaText.classList = "";
    prohodnaText.classList.add("prohodna-text");
    prohodnaText.classList.add("slide-text3");
    image5.classList = "";
    image5.classList.add("img5");
    image5.classList.add("slide-left5");
    image6.classList = "";
    image6.classList.add("img5");
    image6.classList.add("img6");
    image6.classList.add("hidden");
    lakesText.classList = "";
    lakesText.classList.add("lakes-text");
    lakesText.classList.add("slide-text7");
  }
  if (currentImage === 1) {
    galleryImages[currentImage].classList = "";
    galleryImages[currentImage].classList.add("gallery-images");
    galleryImages[currentImage].classList.add("slide-left2");
    rilaText.classList = "";
    rilaText.classList.add("rila-text");
    rilaText.classList.add("slide-text4");
    galleryImages[currentImage + 1].classList = "";
    galleryImages[currentImage + 1].classList.add("gallery-images");
    galleryImages[currentImage + 1].classList.add("slide-left2");
    madaraText.classList = "";
    madaraText.classList.add("madara-text");
    madaraText.classList.add("slide-text5");
    galleryImages[currentImage + 2].classList = "";
    galleryImages[currentImage + 2].classList.add("gallery-images");
    galleryImages[currentImage + 2].classList.add("slide-left2");
    prohodnaText.classList = "";
    prohodnaText.classList.add("prohodna-text");
    prohodnaText.classList.add("slide-text6");
    galleryImages[0].classList = "";
    galleryImages[0].classList.add("gallery-images");
    galleryImages[0].classList.add("slide-left");
    srebarnaText.classList = "";
    srebarnaText.classList.add("srebarna-text");
    srebarnaText.classList.add("hidden");
    image5.classList = "";
    image5.classList.add("img5");
    image5.classList.add("slide-left6");
    image6.classList = "";
    image6.classList.add("img5");
    image6.classList.add("img6");
    image6.classList.add("slide-left5");
    lakesText.classList = "";
    lakesText.classList.add("lakes-text");
    lakesText.classList.add("slide-text8");
    belintashText.classList = "";
    belintashText.classList.add("belintash-text");
    belintashText.classList.add("slide-text7");
  }
  if (currentImage === 2) {
    galleryImages[currentImage].classList.add("slide-left3");
    madaraText.classList.remove("slide-text2");
    madaraText.classList.remove("slide-text5");
    madaraText.classList.add("slide-text");
    galleryImages[currentImage + 1].classList.add("slide-left3");
    prohodnaText.classList.remove("slide-text3");
    prohodnaText.classList.remove("slide-text6");
    prohodnaText.classList.add("slide-text1");
    galleryImages[0].classList.add("slide-left");
    image5.classList.remove("slide-left6");
    image5.classList.add("slide-left7");
    image6.classList.remove("slide-left5");
    image6.classList.add("slide-left6");
    image7.classList.remove("hidden");
    image7.classList.add("img5");
    image7.classList.add("slide-left5");
    lakesText.classList.remove("slide-text8");
    lakesText.classList.add("slide-text9");
    belintashText.classList.remove("slide-text7");
    belintashText.classList.add("slide-text8");
    throatText.classList.remove("hidden");
    throatText.classList.remove("slide-text11");
    throatText.classList.add("slide-text7");
  }
  if (currentImage === 3) {
    galleryImages[currentImage].classList = "";
    galleryImages[currentImage].classList.add("gallery-images");
    galleryImages[currentImage].classList.add("slide-left");
    prohodnaText.classList = "";
    prohodnaText.classList.add("prohodna-text");
    prohodnaText.classList.add("slide-text");
    galleryImages[0].classList = "";
    galleryImages[0].classList.add("gallery-images");
    galleryImages[0].classList.add("slide-left");
    srebarnaText.classList = "";
    srebarnaText.classList.add("srebarna-text");
    srebarnaText.classList.add("slide-left");
    image5.classList = "";
    image5.classList.add("img5");
    image5.classList.add("slide-left8");
    image6.classList = "";
    image6.classList.add("img5");
    image6.classList.add("img6");
    image6.classList.add("slide-left7");
    image7.classList = "";
    image7.classList.add("img5");
    image7.classList.add("img7");
    image7.classList.add("slide-left6");
    image8.classList = "";
    image8.classList.add("img5");
    image8.classList.add("img8");
    image8.classList.add("slide-left5");
    lakesText.classList = "";
    lakesText.classList.add("lakes-text");
    lakesText.classList.add("slide-text10");
    belintashText.classList = "";
    belintashText.classList.add("belintash-text");
    belintashText.classList.add("slide-text9");
    throatText.classList = "";
    throatText.classList.add("throat-text");
    throatText.classList.add("slide-text8");
    bridgesText.classList = "";
    bridgesText.classList.add("bridges-text");
    bridgesText.classList.add("slide-text7");
    galleryImages[0].classList.add("hidden");
    [...galleryImages].forEach((image) => {
      image.classList.add("hidden");
    });
  }
  if (currentImage === 4) {
    galleryImages[currentImage - 1].classList = "";
    galleryImages[currentImage - 1].classList.add("gallery-images");
    galleryImages[currentImage - 1].classList.add("hidden");
    image5.classList = "";
    image5.classList.add("img5");
    image5.classList.add("slide-left9");
    lakesText.classList = "";
    lakesText.classList.add("lakes-text");
    lakesText.classList.add("slide-text11");
    image6.classList = "";
    image6.classList.add("img5");
    image6.classList.add("img6");
    image6.classList.add("slide-left8");
    belintashText.classList = "";
    belintashText.classList.add("belintash-text");
    belintashText.classList.add("slide-text10");
    image7.classList = "";
    image7.classList.add("img5");
    image7.classList.add("img7");
    image7.classList.add("slide-left7");
    throatText.classList = "";
    throatText.classList.add("throat-text");
    throatText.classList.add("slide-text9");
    image8.classList = "";
    image8.classList.add("img5");
    image8.classList.add("img8");
    image8.classList.add("slide-left6");
    bridgesText.classList = "";
    bridgesText.classList.add("bridges-text");
    bridgesText.classList.add("slide-text8");
    galleryImages[0].classList = "";
    galleryImages[0].classList.add("gallery-images");
    galleryImages[0].classList.add("slide-left10");
    srebarnaText.classList = "";
    srebarnaText.classList.add("srebarna-text");
    srebarnaText.classList.add("slide-text7");
  }
  if (currentImage === 5) {
    image6.classList = "";
    image6.classList.add("slide-left9");
    belintashText.classList = "";
    belintashText.classList.add("belintash-text");
    belintashText.classList.add("slide-text11");
    image7.classList = "";
    image7.classList.add("img5");
    image7.classList.add("img7");
    image7.classList.add("slide-left8");
    throatText.classList = "";
    throatText.classList.add("throat-text");
    throatText.classList.add("slide-text10");
    image8.classList = "";
    image8.classList.add("img5");
    image8.classList.add("img8");
    image8.classList.add("slide-left7");
    bridgesText.classList = "";
    bridgesText.classList.add("bridges-text");
    bridgesText.classList.add("slide-text9");
    galleryImages[0].classList = "";
    galleryImages[0].classList.add("gallery-images");
    galleryImages[0].classList.add("slide-left11");
    srebarnaText.classList = "";
    srebarnaText.classList.add("srebarna-text");
    srebarnaText.classList.add("slide-text3");
    galleryImages[1].classList = "";
    galleryImages[1].classList.add("gallery-images");
    galleryImages[1].classList.add("slide-left12");
    rilaText.classList = "";
    rilaText.classList.add("rila-text");
    rilaText.classList.add("slide-text7");
  }
  if (currentImage === 6) {
    image7.classList = "";
    image7.classList.add("img5");
    image7.classList.add("img7");
    image7.classList.add("slide-left9");
    throatText.classList = "";
    throatText.classList.add("throat-text");
    throatText.classList.add("slide-text11");
    image8.classList = "";
    image8.classList.add("img5");
    image8.classList.add("img8");
    image8.classList.add("slide-left8");
    bridgesText.classList = "";
    bridgesText.classList.add("bridges-text");
    bridgesText.classList.add("slide-text10");
    galleryImages[0].classList = "";
    galleryImages[0].classList.add("gallery-images");
    galleryImages[0].classList.add("slide-left13");
    srebarnaText.classList = "";
    srebarnaText.classList.add("srebarna-text");
    srebarnaText.classList.add("slide-text6");
    galleryImages[1].classList = "";
    galleryImages[1].classList.add("gallery-images");
    galleryImages[1].classList.add("slide-left14");
    rilaText.classList = "";
    rilaText.classList.add("rila-text");
    rilaText.classList.add("slide-text8");
    galleryImages[2].classList = "";
    galleryImages[2].classList.add("gallery-images");
    galleryImages[2].classList.add("slide-left15");
    madaraText.classList = "";
    madaraText.classList.add("madara-text");
    madaraText.classList.add("slide-text7");
  }
  if (currentImage === 7) {
    // madaraText.classList.remove("slide-text13");
    // prohodnaText.classList.remove("slide-text12");
    // image8.classList.remove("slide-left22");
    // srebarnaText.classList.remove("slide-text15");
    // rilaText.classList.remove("slide-text14");

    image8.classList = "";
    image8.classList.add("img5");
    image8.classList.add("img8");
    image8.classList.add("slide-left9");
    bridgesText.classList = "";
    bridgesText.classList.add("bridges-text");
    bridgesText.classList.add("slide-text11");
    galleryImages[0].classList = "";
    galleryImages[0].classList.add("gallery-images");
    galleryImages[0].classList.add("slide-left16");
    srebarnaText.classList = "";
    srebarnaText.classList.add("srebarna-text");
    srebarnaText.classList.add("slide-text1");
    galleryImages[1].classList = "";
    galleryImages[1].classList.add("gallery-images");
    galleryImages[1].classList.add("slide-left17");
    rilaText.classList = "";
    rilaText.classList.add("rila-text");
    rilaText.classList.add("slide-text2");
    galleryImages[2].classList = "";
    galleryImages[2].classList.add("gallery-images");
    galleryImages[2].classList.add("slide-left18");
    madaraText.classList = "";
    madaraText.classList.add("madara-text");
    madaraText.classList.add("slide-text3");
    galleryImages[3].classList = "";
    galleryImages[3].classList.add("gallery-images");
    galleryImages[3].classList.add("slide-left19");
    prohodnaText.classList = "";
    prohodnaText.classList.add("prohodna-text");
    prohodnaText.classList.add("slide-text7");
  }
  currentImage++;
});
btnAfter.addEventListener("click", function () {
  console.log(currentImage);

  if (currentImage === 8 || currentImage === -1) {
    currentImage = 0;
  }
  if (currentImage === -1) {
    galleryImages[3];
  }
  if (currentImage == 0) {
    galleryImages[3].classList = "";
    galleryImages[3].classList.add("gallery-images");
    galleryImages[3].classList.add("slide-left20");
    prohodnaText.classList.remove("slide-text18");
    prohodnaText.classList.add("slide-text12");
    galleryImages[2].classList = "";
    galleryImages[2].classList.add("gallery-images");
    galleryImages[2].classList.add("slide-left21");
    madaraText.classList.remove("slide-text19");
    madaraText.classList.add("slide-text13");
    galleryImages[1].classList = "";
    galleryImages[1].classList.add("gallery-images");
    galleryImages[1].classList.add("slide-left21");
    rilaText.classList.remove("slide-text20");
    rilaText.classList.add("slide-text14");
    galleryImages[0].classList = "";
    galleryImages[0].classList.add("gallery-images");
    galleryImages[0].classList.add("slide-left21");
    srebarnaText.classList.remove("slide-text21");
    srebarnaText.classList.add("slide-text15");
    image8.classList.remove("hidden");
    image8.classList.add("img5");
    image8.classList.add("slide-left22");
    bridgesText.classList.remove("hidden");
    bridgesText.classList.add("slide-text16");
    lakesText.classList = "";
    lakesText.classList.add("lakes-text");
    lakesText.classList.add("hidden");
    image5.classList = "";
    image5.classList.add("img5");
    image5.classList.add("hidden");
  }
  if (currentImage === 1) {
    image5.classList = "";
    image5.classList.add("img5");
    image5.classList.add("slide-left23");
    lakesText.classList = "";
    lakesText.classList.add("lakes-text");
    lakesText.classList.add("slide-text17");
    galleryImages[3].classList = "";
    galleryImages[3].classList.add("gallery-images");
    galleryImages[3].classList.add("slide-left24");
    prohodnaText.classList = "";
    prohodnaText.classList.add("prohodna-text");
    prohodnaText.classList.add("slide-text18");
    galleryImages[2].classList = "";
    galleryImages[2].classList.add("gallery-images");
    galleryImages[2].classList.add("slide-left24");
    madaraText.classList = "";
    madaraText.classList.add("madara-text");
    madaraText.classList.add("slide-text19");
    galleryImages[1].classList = "";
    galleryImages[1].classList.add("gallery-images");
    galleryImages[1].classList.add("slide-left24");
    rilaText.classList = "";
    rilaText.classList.add("rila-text");
    rilaText.classList.add("slide-text20");
    galleryImages[0].classList = "";
    galleryImages[0].classList.add("gallery-images");
    galleryImages[0].classList.add("slide-left24");
    srebarnaText.classList = "";
    srebarnaText.classList.add("srebarna-text");
    srebarnaText.classList.add("slide-text21");
  }
  currentImage--;
});
